---
apiVersion: apps/v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-01-24T05:41:38Z"
    generation: 2
    labels:
      olm.deployment-spec-hash: 866c555f4b
      olm.owner: datagrid-operator.v8.2.8
      olm.owner.kind: ClusterServiceVersion
      olm.owner.namespace: eap
      operators.coreos.com/datagrid.eap: ""
    managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:olm.deployment-spec-hash: {}
            f:olm.owner: {}
            f:olm.owner.kind: {}
            f:olm.owner.namespace: {}
            f:operators.coreos.com/datagrid.eap: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"1fbad453-a873-40a2-8252-efd36a16cbe0"}: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:alm-examples: {}
                f:capabilities: {}
                f:categories: {}
                f:certified: {}
                f:containerImage: {}
                f:createdAt: {}
                f:description: {}
                f:olm.operatorGroup: {}
                f:olm.operatorNamespace: {}
                f:olm.targetNamespaces: {}
                f:operatorframework.io/properties: {}
                f:operators.openshift.io/infrastructure-features: {}
                f:repository: {}
                f:support: {}
              f:labels:
                .: {}
                f:name: {}
            f:spec:
              f:containers:
                k:{"name":"infinispan-operator"}:
                  .: {}
                  f:command: {}
                  f:env:
                    .: {}
                    k:{"name":"INFINISPAN_OPERATOR_POD_TARGET_LABELS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"OPERATOR_CONDITION_NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"OPERATOR_NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POD_NAME"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:fieldRef: {}
                    k:{"name":"RELATED_IMAGE_OPENJ9"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"RELATED_IMAGE_OPENJDK"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"WATCH_NAMESPACE"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:fieldRef: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":60000,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:serviceAccount: {}
              f:serviceAccountName: {}
              f:terminationGracePeriodSeconds: {}
      manager: olm
      operation: Update
      time: "2022-01-24T05:41:38Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2022-01-24T05:41:53Z"
    name: infinispan-operator-new-deploy
    namespace: eap
    ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: ClusterServiceVersion
      name: datagrid-operator.v8.2.8
      uid: 1fbad453-a873-40a2-8252-efd36a16cbe0
    resourceVersion: "1149763"
    uid: e3263b20-94bd-493c-8b86-b95182dda976
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 1
    selector:
      matchLabels:
        name: infinispan-operator
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          alm-examples: |-
            [
              {
                "apiVersion": "infinispan.org/v1",
                "kind": "Infinispan",
                "metadata": {
                  "name": "example-infinispan"
                },
                "spec": {
                  "replicas": 1
                }
              },
              {
                "apiVersion": "infinispan.org/v2alpha1",
                "kind": "Backup",
                "metadata": {
                  "name": "example-backup"
                },
                "spec": {
                  "cluster": "example-infinispan",
                  "container": {
                    "cpu": "1000m",
                    "extraJvmOpts": "-Djava.property=me",
                    "memory": "1Gi"
                  }
                }
              },
              {
                "apiVersion": "infinispan.org/v2alpha1",
                "kind": "Cache",
                "metadata": {
                  "name": "example-cache"
                },
                "spec": {
                  "adminAuth": {
                    "secretName": "basic-auth"
                  },
                  "clusterName": "example-infinispan",
                  "name": "mycache"
                }
              },
              {
                "apiVersion": "infinispan.org/v2alpha1",
                "kind": "Restore",
                "metadata": {
                  "name": "example-restore"
                },
                "spec": {
                  "cluster": "example-infinispan",
                  "container": {
                    "cpu": "1000m",
                    "extraJvmOpts": "-Djava.property=me",
                    "memory": "1Gi"
                  }
                }
              },
              {
                "apiVersion": "infinispan.org/v2alpha1",
                "kind": "Batch",
                "metadata": {
                  "name": "example-batch"
                },
                "spec": {
                  "cluster": "example-infinispan",
                  "config": "create cache --template=org.infinispan.DIST_SYNC batch-cache"
                }
              }
            ]
          capabilities: Deep Insights
          categories: Database
          certified: "false"
          containerImage: registry.redhat.io/datagrid/datagrid-8-rhel8-operator@sha256:1435aa60e8ab4d25c86daae68dcb93d14999f50d7c1e11a3c5726a86d3d30453
          createdAt: "2021-08-24T17:39:44Z"
          description: Create and manage Red Hat Data Grid clusters.
          olm.operatorGroup: eap-dwzms
          olm.operatorNamespace: eap
          olm.targetNamespaces: eap
          operatorframework.io/properties: '{"properties":[{"type":"olm.package","value":{"packageName":"datagrid","version":"8.2.8"}},{"type":"olm.gvk","value":{"group":"infinispan.org","kind":"Infinispan","version":"v1"}},{"type":"olm.gvk","value":{"group":"infinispan.org","kind":"Restore","version":"v2alpha1"}},{"type":"olm.gvk","value":{"group":"infinispan.org","kind":"Backup","version":"v2alpha1"}},{"type":"olm.gvk","value":{"group":"infinispan.org","kind":"Batch","version":"v2alpha1"}},{"type":"olm.gvk","value":{"group":"infinispan.org","kind":"Cache","version":"v2alpha1"}}]}'
          operators.openshift.io/infrastructure-features: '["Disconnected"]'
          repository: https://github.com/infinispan/infinispan-operator
          support: Red Hat
        creationTimestamp: null
        labels:
          name: infinispan-operator
      spec:
        containers:
        - command:
          - infinispan-operator
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['olm.targetNamespaces']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: infinispan-operator
          - name: RELATED_IMAGE_OPENJDK
            value: registry.redhat.io/datagrid/datagrid-8-rhel8@sha256:4d8057709958ef60bcabdcec52f05eae8df121fd3f4762c3218abca38130f638
          - name: RELATED_IMAGE_OPENJ9
            value: registry.redhat.io/datagrid/datagrid-8-openj9-11-rhel8@sha256:c8607d6538a7528e27e6ecb138e0a93a03b3c9fa1f8a9a5aad3fd9f4a6814448
          - name: INFINISPAN_OPERATOR_POD_TARGET_LABELS
            value: |
              {"com.redhat.component-name": "Data_Grid", "com.redhat.component-type": "application", "com.redhat.component-version": "8.2.3", "com.redhat.product-name": "Red_Hat_Runtimes", "com.redhat.product-version": "2022-Q1"}
          - name: OPERATOR_CONDITION_NAME
            value: datagrid-operator.v8.2.8
          image: registry.redhat.io/datagrid/datagrid-8-rhel8-operator@sha256:1435aa60e8ab4d25c86daae68dcb93d14999f50d7c1e11a3c5726a86d3d30453
          imagePullPolicy: Always
          name: infinispan-operator
          ports:
          - containerPort: 60000
            name: metrics
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: infinispan-operator
        serviceAccountName: infinispan-operator
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-01-24T05:41:53Z"
      lastUpdateTime: "2022-01-24T05:41:53Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-01-24T05:41:38Z"
      lastUpdateTime: "2022-01-24T05:41:53Z"
      message: ReplicaSet "infinispan-operator-new-deploy-85ff7fbc49" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "4"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"verify-cluster:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"verify-cluster\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2022-01-24T05:57:17Z"
    generation: 6
    labels:
      app: verify-cluster
      app.kubernetes.io/component: verify-cluster
      app.kubernetes.io/instance: verify-cluster
    managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:spec:
              f:containers:
                k:{"name":"verify-cluster"}:
                  f:image: {}
      manager: openshift-controller-manager
      operation: Update
      time: "2022-01-24T05:58:13Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:image.openshift.io/triggers: {}
            f:openshift.io/generated-by: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:openshift.io/generated-by: {}
              f:labels:
                .: {}
                f:deployment: {}
            f:spec:
              f:containers:
                k:{"name":"verify-cluster"}:
                  .: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":8080,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                    k:{"containerPort":8443,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                    k:{"containerPort":8778,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/opt/eap/extensions"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"jboss-cli"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:name: {}
                  f:name: {}
      manager: oc
      operation: Update
      time: "2022-01-24T06:00:10Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2022-01-24T06:05:24Z"
    name: verify-cluster
    namespace: eap
    resourceVersion: "1156267"
    uid: c5bfcb84-21f5-4657-afb6-d373480cfc7d
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: verify-cluster
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: verify-cluster
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/eap/verify-cluster@sha256:34110d4eef2737b0dd3c43ebb5f0dacaf5d2a3afcfe94f72ee87b74e0b8e7317
          imagePullPolicy: IfNotPresent
          name: verify-cluster
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/eap/extensions
            name: jboss-cli
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 511
            name: jboss-cli
          name: jboss-cli
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2022-01-24T05:57:17Z"
      lastUpdateTime: "2022-01-24T06:00:13Z"
      message: ReplicaSet "verify-cluster-6fb5b7db74" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-01-24T06:05:24Z"
      lastUpdateTime: "2022-01-24T06:05:24Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 6
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
kind: DeploymentList
metadata:
  resourceVersion: "1160729"
