---
apiVersion: apps/v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      openshift.io/display-name: Infinispan Cluster
      openshift.io/documentation-url: http://infinispan.org/documentation/
    creationTimestamp: "2022-01-24T05:46:48Z"
    generation: 1
    managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/display-name: {}
            f:openshift.io/documentation-url: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"e4f5d2bd-d94d-47d6-a0d0-f1cfab23999f"}: {}
        f:spec:
          f:podManagementPolicy: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:updateDate: {}
              f:labels:
                .: {}
                f:app: {}
                f:clusterName: {}
                f:com.redhat.component-name: {}
                f:com.redhat.component-type: {}
                f:com.redhat.component-version: {}
                f:com.redhat.product-name: {}
                f:com.redhat.product-version: {}
                f:infinispan_cr: {}
            f:spec:
              f:affinity:
                .: {}
                f:podAntiAffinity:
                  .: {}
                  f:preferredDuringSchedulingIgnoredDuringExecution: {}
              f:containers:
                k:{"name":"infinispan"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"ADMIN_IDENTITIES_HASH"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"ADMIN_IDENTITIES_PATH"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"CONFIG_HASH"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"CONFIG_PATH"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"DEFAULT_IMAGE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"EXTRA_JAVA_OPTIONS"}:
                      .: {}
                      f:name: {}
                    k:{"name":"IDENTITIES_HASH"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"IDENTITIES_PATH"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"JAVA_OPTIONS"}:
                      .: {}
                      f:name: {}
                    k:{"name":"MANAGED_ENV"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:livenessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":8888,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                    k:{"containerPort":11222,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                    k:{"containerPort":11223,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:readinessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:startupProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/etc/config"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/etc/security/admin"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/etc/security/user"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/opt/infinispan/server/data"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"admin-identities-volume"}:
                  .: {}
                  f:name: {}
                  f:secret:
                    .: {}
                    f:defaultMode: {}
                    f:secretName: {}
                k:{"name":"config-volume"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:name: {}
                  f:name: {}
                k:{"name":"identities-volume"}:
                  .: {}
                  f:name: {}
                  f:secret:
                    .: {}
                    f:defaultMode: {}
                    f:secretName: {}
          f:updateStrategy:
            f:type: {}
          f:volumeClaimTemplates: {}
      manager: infinispan-operator
      operation: Update
      time: "2022-01-24T05:46:48Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:availableReplicas: {}
          f:collisionCount: {}
          f:currentReplicas: {}
          f:currentRevision: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updateRevision: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2022-01-24T05:47:30Z"
    name: eap-infinispan
    namespace: eap
    ownerReferences:
    - apiVersion: infinispan.org/v1
      blockOwnerDeletion: true
      controller: true
      kind: Infinispan
      name: eap-infinispan
      uid: e4f5d2bd-d94d-47d6-a0d0-f1cfab23999f
    resourceVersion: "1151637"
    uid: d686df9d-b608-4cfe-b1cf-fc49ff08e237
  spec:
    podManagementPolicy: OrderedReady
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: infinispan-pod
        clusterName: eap-infinispan
        infinispan_cr: eap-infinispan
    serviceName: ""
    template:
      metadata:
        annotations:
          updateDate: 2022-01-24 05:46:48.314309499 +0000 UTC m=+295.280083074
        creationTimestamp: null
        labels:
          app: infinispan-pod
          clusterName: eap-infinispan
          com.redhat.component-name: Data_Grid
          com.redhat.component-type: application
          com.redhat.component-version: 8.2.3
          com.redhat.product-name: Red_Hat_Runtimes
          com.redhat.product-version: 2022-Q1
          infinispan_cr: eap-infinispan
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: infinispan-pod
                    clusterName: eap-infinispan
                    infinispan_cr: eap-infinispan
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: CONFIG_PATH
            value: /etc/config/infinispan.yaml
          - name: MANAGED_ENV
            value: "TRUE"
          - name: JAVA_OPTIONS
          - name: EXTRA_JAVA_OPTIONS
          - name: DEFAULT_IMAGE
            value: registry.redhat.io/datagrid/datagrid-8-rhel8@sha256:4d8057709958ef60bcabdcec52f05eae8df121fd3f4762c3218abca38130f638
          - name: ADMIN_IDENTITIES_PATH
            value: /etc/security/admin/identities.yaml
          - name: IDENTITIES_PATH
            value: /etc/security/user/identities.yaml
          - name: CONFIG_HASH
            value: 099f5093255eba7f644ad75a118525271830e637
          - name: ADMIN_IDENTITIES_HASH
            value: 8ca1083ed95040ba9b977473ad22d0db4c7514c7
          - name: IDENTITIES_HASH
            value: 6824d05e82e126a228218c39abab94ddd74de051
          image: registry.redhat.io/datagrid/datagrid-8-rhel8@sha256:4d8057709958ef60bcabdcec52f05eae8df121fd3f4762c3218abca38130f638
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: rest/v2/cache-managers/default/health/status
              port: 11223
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 80
          name: infinispan
          ports:
          - containerPort: 11223
            name: infinispan-adm
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          - containerPort: 11222
            name: infinispan
            protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: rest/v2/cache-managers/default/health/status
              port: 11223
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: rest/v2/cache-managers/default/health/status
              port: 11223
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 80
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/config
            name: config-volume
          - mountPath: /opt/infinispan/server/data
            name: data-volume
          - mountPath: /etc/security/admin
            name: admin-identities-volume
          - mountPath: /etc/security/user
            name: identities-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: eap-infinispan-configuration
          name: config-volume
        - name: admin-identities-volume
          secret:
            defaultMode: 420
            secretName: eap-infinispan-generated-operator-secret
        - name: identities-volume
          secret:
            defaultMode: 420
            secretName: eap-infinispan-generated-secret
    updateStrategy:
      type: RollingUpdate
    volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: data-volume
        namespace: eap
        ownerReferences:
        - apiVersion: infinispan.org/v1
          blockOwnerDeletion: false
          controller: true
          kind: Infinispan
          name: eap-infinispan
          uid: e4f5d2bd-d94d-47d6-a0d0-f1cfab23999f
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  status:
    availableReplicas: 2
    collisionCount: 0
    currentReplicas: 2
    currentRevision: eap-infinispan-7866954445
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updateRevision: eap-infinispan-7866954445
    updatedReplicas: 2
kind: StatefulSetList
metadata:
  resourceVersion: "1160761"
