---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.128.3.146"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.128.3.146"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/scc: restricted
  creationTimestamp: "2022-01-24T06:05:21Z"
  generateName: verify-cluster-6fb5b7db74-
  labels:
    deployment: verify-cluster
    pod-template-hash: 6fb5b7db74
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/generated-by: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:deployment: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"0dabebd2-d214-43f8-bdc5-8680c3d0a3f2"}: {}
      f:spec:
        f:containers:
          k:{"name":"verify-cluster"}:
            .: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":8080,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
              k:{"containerPort":8443,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
              k:{"containerPort":8778,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/opt/eap/extensions"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"jboss-cli"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-24T06:05:21Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.v1.cni.cncf.io/network-status: {}
          f:k8s.v1.cni.cncf.io/networks-status: {}
    manager: multus
    operation: Update
    time: "2022-01-24T06:05:23Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.128.3.146"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2022-01-24T06:05:24Z"
  name: verify-cluster-6fb5b7db74-cgz6d
  namespace: eap
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: verify-cluster-6fb5b7db74
    uid: 0dabebd2-d214-43f8-bdc5-8680c3d0a3f2
  resourceVersion: "1156262"
  uid: fffa3db3-1257-4717-85c5-a204f60667a8
spec:
  containers:
  - image: image-registry.openshift-image-registry.svc:5000/eap/verify-cluster@sha256:34110d4eef2737b0dd3c43ebb5f0dacaf5d2a3afcfe94f72ee87b74e0b8e7317
    imagePullPolicy: IfNotPresent
    name: verify-cluster
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8443
      protocol: TCP
    - containerPort: 8778
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000660000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/eap/extensions
      name: jboss-cli
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gn7t6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-cqwsq
  nodeName: worker-2.rhdgcluster.lab.upshift.rdu2.redhat.com
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000660000
    seLinuxOptions:
      level: s0:c26,c5
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 511
      name: jboss-cli
    name: jboss-cli
  - name: kube-api-access-gn7t6
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-01-24T06:05:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-01-24T06:05:24Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-01-24T06:05:24Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-01-24T06:05:21Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://927404cb3310cd9ab4c04404b65b7bb3d712a1843ea95e9860c1a8715bd174ab
    image: image-registry.openshift-image-registry.svc:5000/eap/verify-cluster@sha256:34110d4eef2737b0dd3c43ebb5f0dacaf5d2a3afcfe94f72ee87b74e0b8e7317
    imageID: image-registry.openshift-image-registry.svc:5000/eap/verify-cluster@sha256:34110d4eef2737b0dd3c43ebb5f0dacaf5d2a3afcfe94f72ee87b74e0b8e7317
    lastState: {}
    name: verify-cluster
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-01-24T06:05:23Z"
  hostIP: 10.0.89.207
  phase: Running
  podIP: 10.128.3.146
  podIPs:
  - ip: 10.128.3.146
  qosClass: BestEffort
  startTime: "2022-01-24T06:05:21Z"
